name: Auto merge
on: pull_request
jobs:
  merge:  # Dependabotのプルリクエストのみ
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:  # マージに必要なパーミッション
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Github CLIのクレデンシャル
    steps:
      - uses: actions/checkout@v4
      - id: meta  # 依存関係のメタデータを取得
        uses: dependabot/fetch-metadata@v2  # 条件分岐でパッチバージョンかチェック
      - if: >-
          ${{ steps.meta.outputs.package-ecosystem == 'github_actions' && 
            steps.meta.outputs.update-type == 'version-update:semver-patch' }}
        run: |
          gh pr review "${GITHUB_HEAD_REF}" --approve
          gh pr merge "${GITHUB_HEAD_REF}" --merge --auto  # Github CLIでマージ